- hosts: allinone
  become: yes
  become_user: root
  roles:
    - role: common
    - role: langs
    - role: web-bootstrap
    - role: web-go
    - role: web-node
    - role: web-ruby
    - role: web-python
    - role: web-prepare
    - role: bench
